# ----
# Site

title: Fitness.Pullnfit
description: Сервис помогает инструкторам по фитнесу автоматизировать их работу с клиентами с помощью нейросети в области учета и подбора индивидуальных программ тренировок и питания.
url: https://fitness.pullnfit.ru
disqus_shortname: pullnfit
baseurl:

google_site_verification: 
permalink: pretty
timezone: YEKT
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# ----------
# SEO plugin

lang: ru
logo: /siteicon.png
twitter:
  username: Fitness.Pullnfit
facebook:
  publisher: https://www.facebook.com/Fitness.Pullnfit
social:
  name: CloudCannon
  links:
    - https://twitter.com/Fitness.Pullnfit
    - https://www.facebook.com/Fitness.Pullnfit
    - https://plus.google.com/+Fitness.Pullnfit
    - https://www.youtube.com/c/Fitness.Pullnfit
    - https://github.com/Fitness.Pullnfit

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
